-- Godawari Nursery Next.js + NextAuth database schema
-- Target: PostgreSQL / Supabase / Neon / Railway Postgres

create extension if not exists pgcrypto;

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  name text,
  email text not null unique,
  password_hash text not null,
  roles text[] not null default array['customer'],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists plants (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  botanical_name text,
  category text not null,
  price integer not null,
  compare_at_price integer,
  short_description text,
  description text,
  care_level text,
  light text,
  water text,
  height text,
  pot_included boolean not null default true,
  images text[] not null default '{}',
  tags text[] not null default '{}',
  in_stock boolean not null default true,
  stock_count integer not null default 0,
  featured boolean not null default false,
  new_arrival boolean not null default false,
  bestseller boolean not null default false,
  rating numeric(2,1) not null default 0,
  review_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete set null,
  order_number text not null unique,
  customer_name text not null,
  email text not null,
  phone text,
  address text,
  status text not null default 'pending',
  subtotal integer not null default 0,
  total integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  plant_id uuid references plants(id) on delete set null,
  name text not null,
  price integer not null,
  quantity integer not null,
  line_total integer not null
);

create table if not exists reviews (
  id uuid primary key default gen_random_uuid(),
  plant_id uuid references plants(id) on delete cascade,
  name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  subject text,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

-- Demo users. Password hashes below are placeholders; replace with bcrypt hashes generated by your app.
-- The app also supports fallback credentials without a database:
-- admin@godawari.local / admin123 and customer@godawari.local / password

insert into users (name, email, password_hash, roles)
values (
  'Godawari Admin',
  'admin@godawari.local',
  '$2b$12$rebDDX6CqPs7i8u/7DuIk.A6baE0nsZp3VWUvFQiRe35P255x/K0C',
  array['admin']
)
on conflict (email) do update set
  name = excluded.name,
  password_hash = excluded.password_hash,
  roles = excluded.roles,
  updated_at = now();

insert into plants (slug, name, botanical_name, category, price, compare_at_price, short_description, description, care_level, light, water, height, images, tags, in_stock, stock_count, featured, new_arrival, bestseller, rating, review_count)
values
('monstera-deliciosa', 'Monstera Deliciosa', 'Monstera deliciosa', 'indoor', 1450, 1800, 'Sculptural fenestrated leaves for refined homes.', 'A heritage favourite from the Godawari greenhouses.', 'easy', 'Bright, indirect', 'Weekly', '60–90 cm', array['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=1200&q=80'], array['statement','tropical'], true, 24, true, false, true, 4.9, 142),
('fiddle-leaf-fig', 'Fiddle Leaf Fig', 'Ficus lyrata', 'indoor', 2200, 2600, 'An architectural canopy of violin-shaped leaves.', 'Pruned and shaped for a sculptural silhouette.', 'moderate', 'Bright, indirect', 'Every 7–10 days', '90–120 cm', array['https://images.unsplash.com/photo-1597055181449-b3d4f1f8c2b8?w=1200&q=80'], array['statement','designer'], true, 12, true, true, false, 4.7, 88),
('ficus-bonsai', 'Ficus Bonsai', 'Ficus microcarpa', 'bonsai', 4200, 4900, 'A quiet miniature tree with mature character.', 'Hand-shaped bonsai for collectors and calm interiors.', 'moderate', 'Bright, filtered', 'Keep evenly moist', '25–40 cm', array['https://images.unsplash.com/photo-1599598425947-5fbc56e3d59f?w=1200&q=80'], array['bonsai','collector'], true, 8, true, false, true, 4.8, 51)
on conflict (slug) do nothing;
